# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f854c70657e93708da2905ac26a2310983c516116978c667a0b63247e9e7b46ea7face87ece5021f36288561aa072f2db24012efee60b361e9e3f102daad6eca

test:
  secret_key_base: cf79df580c0458943c7c04db86f8ddf27a653625ccb5a61f1a6c8f7990c6e8c9856b446808f06c817502e327b8b6ea4216feacedc7c8b8bd551557809263545d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
